# Generated by Django 4.1.4 on 2023-03-09 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='category title')),
                ('slug', models.SlugField(max_length=55, verbose_name='category slug')),
                ('description', models.TextField(blank=True, verbose_name='category description')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='category image')),
                ('is_active', models.BooleanField(verbose_name='Is Active')),
                ('is_featured', models.BooleanField(verbose_name='Is Featured')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='product title')),
                ('slug', models.SlugField(max_length=150, verbose_name='product slug')),
                ('sku', models.CharField(max_length=255, unique='True', verbose_name='unique product ID (SKU)')),
                ('short_description', models.TextField(verbose_name='short description')),
                ('detail_description', models.TextField(blank='True', null='True', verbose_name='detail description')),
                ('product_image', models.ImageField(blank='True', null='True', upload_to='product', verbose_name='product image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(verbose_name='is active')),
                ('is_featured', models.BooleanField(verbose_name='is featured')),
                ('productStock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.category', verbose_name='product categoy')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Relatedimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='relimg')),
                ('products', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default='1', verbose_name='quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
